---
title: "Notes"
format: html
---

# Praktisk

Vi vil gerne være færdige med indholdet efter næste tirsdag.

Hav god tid til at sætte alt sammen

Husk funktioner skal defineres inde i functions.R

# Plan:

Alle laver hver deres script (kaldet deres navne) og skriver kun i dem her til at starte med.

Vi laver de ting der er skrevet på to do

hvis man finder på andre ting som er nice at undersøge så skriv det på to do og skriv ud i gruppen.

# TO DO

-   PCA af bakteriesammensætning i forskellige lande (KRIS)

-   Finde data på om der er nogen af vores lande som har mere endometriose end andre. (Kris=

-   Find data på hvilke bakterier er mere abundant i folk med endometriose. (Line)

-   Completeness vs contamination (Mathilde)

-   Hvordan kan man ellers kigge kvaliteten af datasættet - er data på kvinders sundhed god nok (Alberte)

    -   Hvordan er completeness fordelt på forskellige phyla? er nogle "bedre" end andre?

    -   Er der forskel på high abundance taxa og low abundance taxa ift kvalitet?

    -   N_contigs: få = god assembly

        -   Correlation mellem N_contigs og completeness?

    -   N50: høj = længere contigs og god assembly

        -   Correlation mellem N50 og genom længde?

    -   Er der forskel på completeness/contamination mellem de meget common (lactobacillus) og mere rare/uncultured (atopobium, gardnerella)?

    -   Completeness/contamination på tværs af geografi

-   Finde formålet med phylogenetisk træ + skrive noget til det.

-   Få skrevet overblik over data rent - basically færdig (Sigrid)

-   Skriv noget om GC content - hvorfor er det relevant? (Sigrid)

    -   identificere atypiske genomer
    -   GC vs Completion/contamination

-   Find data på "normal" GC content. (Sigrid)

### Check list:

-   00_all.qmd

-   01_load.qmd (Done)

-   02_clean.qmd

-   03_augment.qmd

-   04_describe.qmd (Done)

-   05_analysis_1.qmd

-   06_analysis_2.qmd

-   Analysis - GC content

-   Analysis  - MAGs with endometriosis-associated genera
