---
title: "Exploring meta-data of human vaginal microbiome"
subtitle: "Group 6"
author:
  - Alberte Englund
  - Mathilde Due
  - Line Winther Gormsen
  - Sigrid Frandsen
  - Kristine Johansen
  
format: 
  revealjs:
    theme: moon
    self-contained: true
    code-line-numbers: true
    smaller: true
    scroll: true
    transition: slide
editor: visual
---

```{r}
library("tidyverse")
library("readr")
library("broom")
library("here")
library("ggrepel")
```

## Examples:

Bare for at vide de ting vi kan bruge i præsentations-dokumentet. Her skriver jeg i **bold**. Her skriver jeg i *kursiv*. Her skriver jeg i ***bold og kursiv***. Her skriver jeg i [rød]{style="color: red;"}

## Study Description

::: incremental
-   Dataset: The genome meta-data-set from the human vaginal microbiome.
-   Aim: Uncover patterns in genome quality, taxonomic composition, and ecological characteristics, while demonstrating the principles of reproducible and collaborative data science in R.
:::

### Pause

content before the pause

. . .

content after the pause

## Examples:

### Several columns

::::: columns
::: {.column width="40%"}
Left column
:::

::: {.column width="60%"}
Right column
:::
:::::

## Examples: smaller text on slide {.smaller}

slide so you can make things smaller if content can not fit. - Bullet Point 1

-   Bullet Point 2

-   Bullet Point 3

-   Bullet Point 4

-   Bullet Point 5

-   Bullet Point 6

## Examples: scrollable slide {.scrollable}

slide so you can scroll to see the rest of the content if to much. - Bullet Point 1

-   Bullet Point 2

-   Bullet Point 3

-   Bullet Point 4

-   Bullet Point 5

-   Bullet Point 6

-   Bullet Point 7

-   Bullet Point 8

-   Bullet Point 9

-   Bullet Point 10

-   Bullet Point 11

-   Bullet Point 12

-   Bullet Point 13

## Asides and footnotes

### Asides

Slide content

::: aside
Some additional commentary of more peripheral interest.
:::

### Footnotes

-   Green [^1]
-   Brown
-   Purple

[^1]: A footnote

::: aside
Some additional commentary of more peripheral interest.
:::
