---
title: "Load packages and data"
format: html
---

## Download data

First of all, we create directories data and data/\_raw if they don't already exist. Then we download the data from the EBI website below into the raw data directory:

<https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_genomes/human-vaginal/v1.0/genomes-all_metadata.tsv>

```{r}
data_dir <- "../data/"
raw_dir <- "../data/_raw/"
data_file <- "genomes-all_metadata.tsv"
data_loc <- "https://ftp.ebi.ac.uk/pub/databases/metagenomics/mgnify_genomes/human-vaginal/v1.0/"

if( !dir.exists(data_dir)){
  dir.create(path = data_dir)
}
if( !dir.exists(raw_dir) ){
  dir.create(path = raw_dir)
}
if( !file.exists(str_c(raw_dir, data_file)) ){
  download.file(
    url = str_c(data_loc, data_file),
    destfile = str_c(raw_dir, data_file))
}

```

## Load data

The data is a tab separated file separated, so it is loaded into R using read_tsv from the read_r library:

```{r}
readr::read_tsv(file = "../data/_raw/genomes-all_metadata.tsv")
```

# 
